gardensketchpro/gardenplaner/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('plant_types/', views.PlantTypeListView.as_view(), name='plant_types'),
    path('plant_list/', views.PlantListView.as_view(), name='plant_list'),
    path('my_projects/', views.GardenProjectListView.as_view(), name='my_projects'),
    path('create_project/', views.CreateGardenProjectView.as_view(), name='create_project'),
    path('gardenproject_detail/<int:pk>/', views.GardenProjectDetailView.as_view(), name='gardenproject_detail'),
    path('delete_project/<int:pk>/', views.delete_project_view, name='delete_project'),
    path('confirm_delete_project/<int:pk>/', views.confirm_delete_project_view, name='confirm_delete_project'),
    path('zone_detail/<int:pk>/', views.ZoneDetailView.as_view(), name='zone_detail'),
    path('create_zone/<int:project_id>/', views.CreateZoneView.as_view(), name='create_zone'),
    path('zone/<int:zone_id>/plant/add/', views.AddPlantView.as_view(), name='add_plant'),
    path('add_photo/<int:zone_id>/', views.AddPhotoView.as_view(), name='add_photo'),
    
]

gardensketchpro/gardensketchpro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('gardenplaner.urls')),
    path('user/', include('userprofile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]  + (
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

gardensketchpro/userprofile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name="profile"),
    path('profile/update/', views.profile_update, name='profile_update'),
]

gardensketchpro/gardenplaner/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField
from django.urls import reverse
from PIL import Image

User = get_user_model()

class Type(models.Model):
    name_en = models.CharField(_('name in English language'), max_length=100)
    name_lt = models.CharField(_('name in Lithuanian language'),max_length=100)
    description_en = models.TextField(_('description in English language'), max_length=1000, blank=True)
    description_lt = models.TextField(_('description in English language'), max_length=1000, blank=True)
    
    class Meta:
        verbose_name = _("type")
        verbose_name_plural = _("types")

    def __str__(self):
        return self.name_en

    def get_absolute_url(self):
        return reverse("type_detail", kwargs={"pk": self.pk})


class PlantTime(models.Model):
    month_en = models.IntegerField(
        choices=[
            (1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'),
            (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'),
            (11, 'November'), (12, 'December'),
        ]
    )
    month_lt = models.IntegerField(
        choices=[
            (1, 'Sausis'), (2, 'Vasaris'), (3, 'Kovas'), (4, 'Balandis'), (5, 'Gegužė'),
            (6, 'Birželis'), (7, 'Liepa'), (8, 'Rugpjūtis'), (9, 'Rugsėjis'), (10, 'Spalis'),
            (11, 'Lapkritis'), (12, 'Gruodis'),
        ]
    )
    first_day = models.IntegerField(
        choices=[
            (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'),
            (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'),
            (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'),
            (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'),
            (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'),
        ])
    last_day = models.IntegerField(
        choices=[
            (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'),
            (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'),
            (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'),
            (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'),
            (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'),
        ])
    
    class Meta:
        verbose_name = _("plantTime")
        verbose_name_plural = _("plantTimes")

    def __str__(self):
        return f'{self.get_month_en_display()} ({self.get_month_lt_display()})'

    def get_absolute_url(self):
        return reverse("plantingday_detail", kwargs={"pk": self.pk})


class Color(models.Model):
    name_en = models.CharField(_("name in English language"),max_length=100)
    name_lt = models.CharField(_("name in Lithuanian language"),max_length=100)
    description_en = models.TextField(_("description in English language"), max_length=1000, blank=True)
    description_lt = models.TextField(_("description in Lithuanian language"), max_length=1000, blank=True)
    
    class Meta:
        verbose_name = _("color")
        verbose_name_plural = _("colors")

    def __str__(self):
        return self.name_en

    def get_absolute_url(self):
        return reverse("color_detail", kwargs={"pk": self.pk})


class Plant(models.Model):
    name_en = models.CharField(max_length=100)
    name_lt = models.CharField(max_length=100)
    description_en = models.TextField(max_length=1000, blank=True)
    description_lt = models.TextField(max_length=1000, blank=True)
    size = models
    type = models.ForeignKey(
        Type,
        verbose_name=_("type"),
        on_delete=models.CASCADE, 
        related_name=_("plants"),)
    colors = models.ManyToManyField(
        Color,
        verbose_name=_("color"), 
        related_name=_("plants"),
        )
    planting_time = models.ForeignKey(
        PlantTime, 
        verbose_name=_("planting time"),
        on_delete=models.CASCADE,
        related_name=_("plants"))
    
    class Meta:
        verbose_name = _("plant")
        verbose_name_plural = _("plants")

    def __str__(self):
        return self.name_en

    def get_absolute_url(self):
        return reverse("plant_detail", kwargs={"pk": self.pk})
    
#zemiau modelio dalis kuria manipuliuoja vartotojas virsuje
# modelio dalis kiri tvarkoma administratoriaus.

class GardenProject(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name=_("user"),
        on_delete=models.CASCADE,
        related_name=_("garden_projects"),
    )
    project_name = models.CharField(_("project name"), max_length=100)
    public = models.BooleanField(_("public"), default=False)

    class Meta:
        verbose_name = _("garden project")
        verbose_name_plural = _("garden projects")

    def __str__(self):
        return self.project_name

    def get_absolute_url(self):
        return reverse("gardenproject_detail", kwargs={"pk": self.pk})
    

class Zone(models.Model):
    name = models.CharField(_("name in Lithuanian language"), max_length=50, blank=True)
    lenght = models.FloatField(_("enter lenght"))
    width = models.FloatField(_("enter width"))
    garden_project = models.ForeignKey(
        GardenProject,
        verbose_name=_("garden project"),
        on_delete=models.CASCADE,
        related_name=_("zones"),
    )
    public = models.BooleanField(_("public"), default=False)
    
    class Meta:
        verbose_name = _("zone")
        verbose_name_plural = _("zones")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("zone_detail", kwargs={"pk": self.pk})

  
class SelectedPlant(models.Model):
    plant = models.ForeignKey(
        Plant, 
        verbose_name=_("plant"),
        on_delete=models.CASCADE,
        related_name=_("selected_plants"))
    color = models.ForeignKey(
        Color,
        verbose_name=_("color"), 
        on_delete=models.CASCADE,
        related_name=_("selected_plants"))
    blooming_period = models.CharField(_("enter blooming period"), max_length=100, blank=True)
    qty = models.IntegerField(_('enter quantity'))
    price = models.FloatField(_('enter plants price of unit'),)
    zone = models.ForeignKey(
        Zone,
        verbose_name=_("zone"),
        on_delete=models.CASCADE,
        related_name=_("selected_plants")
        )

    class Meta:
        verbose_name = _("selected plant")
        verbose_name_plural = _("selected plants")

    def __str__(self):
        return self.plant

    def get_absolute_url(self):
        return reverse("selectedplant_detail", kwargs={"pk": self.pk}) 


class Photo(models.Model):
    image = models.ImageField(_("add image"), upload_to='photos/', null=True, blank=True)
    season = models.CharField(
        _("select season"), 
        max_length=100, 
        choices=[
            ("SPRING", "SPRING"), 
            ("SUMMER", "SUMMER"), 
            ("AUTUMN", "AUTUMN"), 
            ("WINTER", "WINTER"),
        ])
    zone = models.ForeignKey(
        Zone,
        verbose_name=_("zone"),
        on_delete=models.CASCADE,
        related_name=_("photos")
        )
        

    class Meta:
        verbose_name = _("photo")
        verbose_name_plural = _("photos")

    def save(self, *args, **kwargs) -> None:
        super().save(*args, **kwargs)
        if self.image:
            image = Image.open(self.image.path)
            if image.height > 300 or image.width > 500:
                resized_dimensions = (500, 300)
                image.thumbnail(resized_dimensions)
                image.save(self.image.path)

    def __str__(self):
        return self.image
    
    def get_absolute_url(self):
        if self.image:
            return reverse("zone_detail", kwargs={"pk": self.pk})
        else:
            # Define a default URL or handle the case when there is no image
            return reverse("default_url")
    # def get_absolute_url(self):
    #     return reverse("zone_detail", kwargs={"pk": self.pk})

    


     

gardensketchpro/gardenplaner/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models

class GardenProjectForm(forms.ModelForm):
    class Meta:
        model = models.GardenProject
        fields = ['project_name', 'public', ]
        lables = {
            'project_name': _('project name'),
            'public': _('public'),
        }

class ZoneForm(forms.ModelForm):
    class Meta:
        model = models.Zone
        fields = ['name', 'lenght', 'width', 'public']


class PlantDropdownForm(forms.ModelForm):
    class Meta:
        model = models.SelectedPlant
        fields = ['plant']


class SelectedPlantForm(forms.ModelForm):
    class Meta:
        model = models.SelectedPlant
        fields = ['plant', 'color', 'qty', 'blooming_period', 'price', 'zone']
        widgets = {
            'plant': forms.HiddenInput(),
            'zone': forms.HiddenInput(),
        }


class PhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ['image', 'season']

gardensketchpro/gardenplaner/templates/gardenplaner/add_photo.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Create Zone for {{ garden_project.project_name }}</h2>

  <form method="post" action="{% url 'add_photo' zone_id=zone.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ photo_form.as_p }}
    <button type="submit" class="btn btn-primary">Add Photo</button>
</form>
  <a href="{% url 'zone_detail' project_id=zone.garden_project.pk pk=zone.pk %}" class="btn btn-primary">Back to Zone</a>

{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/add_plant.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Select Plants  </h2>

  <form method="post" action="{{ request.path }}?plant={{ request.GET.plant }}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Add Plant</button>
  </form>

  <h3>Selected Plants</h3>
  <ul>
    {% for plant in object_list %}
      <li>
        <p>Plant: {{ selected_plant.plant.name_en }}</p>
        <p class="card-text">Color: {{ selected_plant.color.name_en }}</p>
        <p class="card-text">Blooming Period: {{ selected_plant.blooming_period }}</p>
        <p class="card-text">Quantity: {{ selected_plant.qty }}</p>
        <p class="card-text">Price: {{ selected_plant.price }}</p>
      </li>
    {% endfor %}
  </ul>

  <a href="{% url 'zone_detail' pk=zone.id %}" class="btn btn-primary">Back to Zone</a>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/confirm_delete_project.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete the project "{{ garden_project.project_name }}"?</p>

  <form method="post" action="{% url 'delete_project' pk=garden_projects.pk %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
  </form>

  <a href="{% url 'gardenproject_detail' pk=garden_project.pk %}" class="btn btn-secondary">No, Cancel</a>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/create_project.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Create a new Garden Project</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Project</button>
  </form>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/create_zone.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Create Zone for {{ garden_project.project_name }}</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ zone_form.as_p }}
    <button type="submit" class="btn btn-primary">Create Zone</button>
  </form>

  <a href="{% url 'gardenproject_detail' pk=garden_project.pk %}" class="btn btn-secondary">Cancel</a>
  

{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/gardenproject_confirm_delete.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete the project "{{ garden_project.project_name }}"?</p>

  <form method="post" action="{% url 'delete_project' pk=garden_project.pk %}" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
  </form>

  <a href="{% url 'gardenproject_detail' pk=garden_project.pk %}" class="btn btn-primary">No, Cancel</a>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/gardenproject_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>{{ garden_project.project_name }} Details</h2>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Project Name: {{ garden_project.project_name }}</h5>
      <p class="card-text">Created by: {{ garden_project.user.username }}</p>
      <p class="card-text">Public: {% if garden_project.public %}Yes{% else %}No{% endif %}</p>
      {% for zone in garden_project.zone.all %}
        <li>
          <p><a href="{% url 'zone_detail' pk=zone.id %}">{{ zone.name }}</a></p>
          <p class="card-text">Length: {{ zone.length }}</p>
          <p class="card-text">Width: {{ zone.width }}</p>
        </li>
      {% endfor %}
      <form method="post" action="{% url 'delete_project' pk=garden_project.id %}" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger"><a href="{% url 'confirm_delete_project' pk=garden_project.id %}">Delete Project</a></button>
      </form>
      
        <button type="submit" class="btn btn-danger"><a href="{% url 'create_zone' project_id=garden_project.id %}" class="btn btn-success">Create Zone</a></button>
    
      <a href="{% url 'my_projects' %}" class="btn btn-primary">Back to My Projects</a>
    </div>
  </div>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/index.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %} Welcome to {{ block.super }}{% endblock title %}
{% block content %}
<body>
    <div class="container">
        <div class="content">
            <div class="main-content">
                <center><h1>{% trans "Bringing Your Garden Dreams to Life!" %}</h1></center>
                <p class="title"><img class="title center" src="{% static '/img/titulinis.jpg' %}"></p>
                <p>Transforming your outdoor space into a captivating garden
                    retreat has never been easier. GardenSketch Pro is your premier tool
                    for turning your garden dreams into reality.
                    Whether you're an experienced gardener or just beginning
                    your gardening journey, our cutting-edge platform is designed
                    to simplify the process of planning and designing your dream garden.</p>
                <p><h3>With GardenSketch Pro, you can:</h3></p>
                <p> Visualize your garden layout with precision and creativity.
                    Explore a vast selection of outdoor plants, trees, and shrubs.
                    Receive personalized recommendations tailored to your location and climate.
                    Create planting schedules and set handy reminders for essential tasks.
                    Collaborate with friends, family, or fellow garden enthusiasts to refine your garden designs.


                    Discover the power of GardenSketch Pro and unlock your garden's full potential.
                    It's time to embark on a gardening adventure that will leave your outdoor space
                    flourishing and beautiful. Let's begin your journey today!</p>
                <ul>
                </ul>
            </div>
        </div>   
    </div>
</body>
{% endblock content %}

gardensketchpro/gardenplaner/templates/gardenplaner/my_projects.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>My Garden Projects</h2>
  <div class="mb-3">
    <a href="{% url 'create_project' %}" class="btn btn-success">Create New Project</a>
  </div>
  <div class="row">
    <div class="col-md-8">
      {% for project in gardenproject_list %}
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">{{ project.project_name }}</h5>
            <p class="card-text">Created by: {{ project.user.username }}</p>
            <a href="{% url 'gardenproject_detail' pk=project.pk %}" class="btn btn-primary">View Details</a>
          </div>
        </div>
      {% endfor %}

      <div class="pagination">
        <span class="step-links">
          {% if gardenproject_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ gardenproject_list.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
            Page {{ gardenproject_list.number }} of {{ gardenproject_list.paginator.num_pages }}.
          </span>

          {% if gardenproject_list.has_next %}
            <a href="?page={{ gardenproject_list.next_page_number }}">next</a>
            <a href="?page={{ gardenproject_list.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    </div>

    <div class="col-md-4">
      <!-- You can include additional content or widgets here -->
    </div>
  </div>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/plant_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}{% trans "plants list" %}{{ block.super }}{% endblock title %}
{% block content %}
<div class="container">
    <div class="background center">
        <div class="content center">
            <div class="main-content">
                <div class="pager">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">{% trans "First" %}</a>
                        {% if page_obj.previous_page_number != 1 %}
                            <a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
                        {% endif %}
                    {% endif %}
                    <span class="current">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }} </span>
                    {% if page_obj.has_next %}
                        {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                            <a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
                        {% endif %}
                        <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "Last" %}</a>
                    {% endif %}
                    {% if search %}
                        <form class="beer-search" method="GET" action="{{ request.path }}">
                            <input type="text" name="query" value="{{ request.GET.query }}" placeholder="{% trans "search beer" %}...">
                            <button type="submit">&#128269;</button>
                            <a href="{{ request.path }}">{% trans "reset" %}</a>
                        </form>
                    {% endif %}
                </div>
                {% if object_list %}
                    <div class="plant-list center">
                        <ul>
                        {% for plant in object_list %}
                            <li class="data-menu center">
                                {% comment %} <h3><a href="{% url 'beer_detail' beer.name %}">{{ beer.name }}</a></h3> {% endcomment %}
                                <p><strong>{% trans "Price"|capfirst %}:</strong> {{ beer.price }}$
                                <strong>{% trans "Available Liters"|capfirst %}:</strong> {{ beer.qty }}
                                <strong>{% trans "Beer Type"|capfirst %}:</strong> {{ beer.beer_type.name }}</p>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                {% else %}
                    <p>{% trans "No plant available" %}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>    
{% endblock content %}

gardensketchpro/gardenplaner/templates/gardenplaner/plant_types.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}{% trans "Plant types"|capfirst %} {{ block.super }}{% endblock title %}
{% block content %}
<h1>{% trans "plant types"|title %}</h1>
{% comment %} {% include "library/inc/pager_prev_next.html" %} {% endcomment %}
<ul class="card-list">
{% for plant_type in object_list %}
    {% include "gardenplaner/inc/plant_types_card.html" %}
{% empty %}
    <p>{% trans "no plant types found"|capfirst %}.</p>
{% endfor %}
</ul>
{% endblock content %}

gardensketchpro/gardenplaner/templates/gardenplaner/selecting_plants.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Select Plants for {{ zone_composition.zone.name_en }}</h2>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Add Plant</button>
  </form>

  <h3>Selected Plants</h3>
  <ul>
    {% for selected_plant in zone.selected_plant.all %}
      <li>
        <p>Plant: {{ selected_plant.plant.name_en }}</p>
        <p class="card-text">Color: {{ selected_plant.color.name_en }}</p>
        <p class="card-text">Blooming Period: {{ selected_plant.blooming_period }}</p>
        <p class="card-text">Quantity: {{ selected_plant.qty }}</p>
        <p class="card-text">Price: {{ selected_plant.price }}</p>
      </li>
    {% endfor %}
  </ul>

  <a href="{% url 'zone_detail' project_id=zone.garden_project.pk pk=zone.pk %}" class="btn btn-primary">Back to Zone</a>
{% endblock %}

gardensketchpro/gardenplaner/templates/gardenplaner/zone_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %} {{ block.super }}{% endblock title %}
{% block content %}
  <h2>Zone Details</h2>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Name : {{ zone.name }}</h5>
      <p class="card-text">Length: {{ zone.lenght }}</p>
      <p class="card-text">Width: {{ zone.width }}</p>
      <p class="card-text">Garden Project: {{ zone.garden_project.project_name }}</p>
    </div>
  </div>
  <form method="GET" action="{% url 'add_plant' zone_id=zone.pk %}">
    {{ plants_dropdown_form.as_p }}
    <button type="submit" class="btn btn-primary">Add Plant</button>
  </form>

  <h3>Selected Plants</h3>
  {{ zone.selected_plants.all }}
  {% for selected_plant in zone.selected_plants.all %}
    <p>Plant: {{ selected_plant.plant.name_en }} - Color: {{ plant.color.name_en }} - Blooming Period: {{ plant.blooming_period }} - Quantity: {{ plant.qty }} - Price: {{ plant.price }}</p>
  {% endfor %}

  <h3>Photos</h3>
  <button><a href="{% url 'add_photo' zone_id=zone.pk %}">ADD Photo</a></button>
  {% for photo in photos %}
    <div>
        {% if photo.image %}
            <img src="{{ photo.image.url }}" alt="Photo">
        {% else %}
            <p>No image available</p>
        {% endif %}
        <p>season: {{ photo.season }}</p>
    </div>
{% endfor %}

  <a href="{% url 'gardenproject_detail' pk=zone.garden_project.pk %}" class="btn btn-primary">Back to Garden Project</a>
{% endblock %}